from typing import List
from ...rim.repository import RepositoryModel
from ...capabilities.model import Capability

class RefinementEngine:
    """
    Refines raw clusters generated by the ClusteringAlgorithm.
    """
    def __init__(self, model: RepositoryModel):
        self.model = model
        
    def refine(self, raw_clusters: List[List[str]]) -> List[List[str]]:
        refined_clusters = []
        
        for cluster in raw_clusters:
            # 1. Filter out tiny clusters (e.g., just 1 generic capability)
            if len(cluster) < 1:
                continue
                
            # If it's 1 capability, we keep it if it's highly confident
            if len(cluster) == 1:
                cap = self.model.capabilities.get(cluster[0])
                if not cap or cap.confidence < 0.5:
                    continue
                    
            # 2. Heuristically, if a cluster is huge (>20), we might want to split it.
            # For this MVP, we just accept it.
            
            refined_clusters.append(cluster)
            
        return refined_clusters
