from enum import Enum

class EntityType(str, Enum):
    # Repository Level
    REPOSITORY = "REPOSITORY"
    WORKSPACE = "WORKSPACE"
    PACKAGE = "PACKAGE"
    MODULE = "MODULE"
    DIRECTORY = "DIRECTORY"
    FILE = "FILE"

    # Code Symbols
    CLASS = "CLASS"
    INTERFACE = "INTERFACE"
    ENUM = "ENUM"
    STRUCT = "STRUCT"
    TYPE_ALIAS = "TYPE_ALIAS"
    FUNCTION = "FUNCTION"
    METHOD = "METHOD"
    VARIABLE = "VARIABLE"
    CONSTANT = "CONSTANT"
    PARAMETER = "PARAMETER"

    # Runtime
    ROUTE = "ROUTE"
    MIDDLEWARE = "MIDDLEWARE"
    CONTROLLER = "CONTROLLER"
    SERVICE = "SERVICE"
    BACKGROUND_JOB = "BACKGROUND_JOB"
    QUEUE = "QUEUE"
    EVENT = "EVENT"
    TOPIC = "TOPIC"
    WORKER = "WORKER"

    # Infrastructure
    DATABASE = "DATABASE"
    TABLE = "TABLE"
    COLUMN = "COLUMN"
    MIGRATION = "MIGRATION"
    CACHE = "CACHE"
    REDIS_KEY = "REDIS_KEY"
    ENVIRONMENT_VARIABLE = "ENVIRONMENT_VARIABLE"
    DOCKER_SERVICE = "DOCKER_SERVICE"
    CONTAINER = "CONTAINER"
    VOLUME = "VOLUME"
    SECRET = "SECRET"

    # Testing
    TEST_SUITE = "TEST_SUITE"
    TEST_CASE = "TEST_CASE"
    FIXTURE = "FIXTURE"
    MOCK = "MOCK"

    # Documentation
    README = "README"
    MARKDOWN_DOC = "MARKDOWN_DOC"
    OPENAPI_SPEC = "OPENAPI_SPEC"

    # External
    DEPENDENCY = "DEPENDENCY"
    LIBRARY = "LIBRARY"
    PACKAGE_REFERENCE = "PACKAGE_REFERENCE"
    API_ENDPOINT = "API_ENDPOINT"
    CLOUD_RESOURCE = "CLOUD_RESOURCE"


class RelationshipType(str, Enum):
    DECLARES = "DECLARES"
    IMPORTS = "IMPORTS"
    CALLS = "CALLS"
    USES = "USES"
    READS = "READS"
    WRITES = "WRITES"
    RETURNS = "RETURNS"
    THROWS = "THROWS"
    IMPLEMENTS = "IMPLEMENTS"
    INHERITS = "INHERITS"
    BELONGS_TO = "BELONGS_TO"
    EXPOSES = "EXPOSES"
    DEPENDS_ON = "DEPENDS_ON"
    REFERENCES = "REFERENCES"
    CONFIGURES = "CONFIGURES"
    CONNECTS_TO = "CONNECTS_TO"
    LISTENS_TO = "LISTENS_TO"
    PUBLISHES = "PUBLISHES"
    TESTS = "TESTS"
